import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
	container: {
		flex: 1,
		justifyContent: 'center',
		alignItems: 'center',
		backgroundColor: '#FFEADD',
	},
	ArticlesContainer: {
		display: 'flex',
	},
	article: {
		backgroundColor: 'white',
		display: 'flex',
		flexDirection: 'column',
		justifyContent: 'space-between',
		alignItems: 'center',
		padding: 20,
		borderRadius: 12,
		gap: 20,
		marginVertical: 20,
	},
	firstArticle: {
		backgroundColor: 'white',
		display: 'flex',
		flexDirection: 'column',
		justifyContent: 'space-between',
		alignItems: 'center',
		padding: 20,
		borderRadius: 12,
		gap: 20,
		marginVertical: 20,
		marginLeft: 30,
	},
	articleImg: {
		height: 140,
		width: '100%',
		borderRadius: 4,
	},
	scrollArticles: {
		marginHorizontal: 30,
		height: 270,
	},
	topScrollArticles: {
		height: 250,
		width: 300,
		marginRight: 30,
	},
	topScrollArticlesImg: {
		height: 120,
		width: '95%',
	},
	h1: {
		fontSize: 24,
		fontWeight: 'bold',
	},
	pagesView: {
		display: 'flex',
		flexDirection: 'row',
		justifyContent: 'space-around',
		backgroundColor: 'rgba(255, 255, 255, 0)',
		width: '100%',
		padding: 10,
	},
	page: {
		backgroundColor: 'white',
		fontSize: 24,
		color: '#FFEADD',
		paddingVertical: 10,
		paddingHorizontal: 18,
		textAlign: 'center',
		borderRadius: 50,
	},
	currentPage: {
		backgroundColor: '#FF6666',
		fontSize: 24,
		color: 'white',
		paddingVertical: 10,
		paddingHorizontal: 18,
		textAlign: 'center',
		borderRadius: 50,
	},
	headerContainer: {
		backgroundColor: '#FF6666',
		justifyContent: 'center',
		alignItems: 'center',
		height: 50,
		padding: 10,
	},
	headerTitle: {
		fontSize: 26,
		fontWeight: 'bold',
		color: 'white',
	},
	scrollNews: {
		borderBottomWidth: 5,
		borderBottomColor: '#FF6666',
		marginBottom: 10,
	},
	scrollNew: {
		backgroundColor: 'black',
		padding: 30,
	},
	articlePageContainer: {
		padding: 30,
	},
	articlePageImg: {
		height: 240,
		width: '100%',
		borderRadius: 4,
		marginBottom: 10,
	},
	smallText: {
		fontSize: 16,
		color: 'gray',
	},
	boldText: {
		fontSize: 35,
		fontWeight: 'bold',
		marginTop: 25,
		marginBottom: 25,
	},
	readBtn: {
		backgroundColor: '#FF6666',
		paddingHorizontal: 5,
		paddingVertical: 1,
		width: '100%',
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: 8,
		marginBottom: 100,
	},
	readBtnHover: {
		backgroundColor: '#FCAEAE',
		paddingHorizontal: 5,
		paddingVertical: 1,
		width: '100%',
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: 8,
		marginBottom: 100,
		color: '#FCAEAE',
	},
});
